apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi-test
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ghcr.io/fahad-shaikh09/backstage:latest
          ports:
            - containerPort: 8080
