apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: demisto/fastapi:0.125.0.9094740
          ports:
            - containerPort: 8080
